name: Artifact ReactApp
permissions:
    contents: write
on:
    workflow_dispatch:
jobs:
    tests:
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - name: Install node 
              uses: actions/setup-node@v4
              with:
                node-version: 22
            - name: Install npm
              run: npm install
            - name: Test
              run: npm run test > test.txt
            - name: Upload test
              uses: actions/upload-artifact@v4
              with:
                name: testing
                path: test.txt
    download-test:
        name: Download Test
        runs-on: ubuntu-latest
        needs: tests
        steps:
            - name: DownloadTest
              uses: actions/download-artifact@v4
              with:
                name: testing
                path: test.txt
            - name: Print result
              shell: bash
              run: |
                value=`cat test.txt`
                echo $value
