name: Artifact ReactApp
permissions:
  contents: write
on:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install npm dependencies
        run: npm install

      - name: Run Tests and Save Results
        run: npm run test > test.txt

      - name: Upload Test Results as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: testing
          path: test.txt

  download-test:
    name: Download and Print Test Results
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - name: Download Test Results
        uses: actions/download-artifact@v4
        with:
          name: testing
          path: downloaded-artifact  

      - name: Print Test Results
        shell: bash
        run: |
          # Vérifier la structure du dossier téléchargé
          ls -la downloaded-artifact

          # Lire le fichier test.txt depuis le dossier
          value=$(cat downloaded-artifact/test.txt)
          echo "Test Results:"
          echo "$value"